    <tr>
      <td colspan="2">
	<table width="100%" callpadding="0" cellspacing="0" border="0">
	  <tr align="center">
	    <td></td>
	    <td align="right">
	      <input class="button" type="submit" name="submit" 
		     value="<? $submit_title ?>" 
		     onclick="document.<?= $formname ?>.submit();" />
	      <input class="button" type="reset" name="reset" value="Reset" />
	    </td>
	  </tr>
	</table>
      </td>
    </tr>
  </table>

